quarkus.langchain4j.ollama.timeout=180s
quarkus.langchain4j.ollama.chat-model.model-id=qwen3:8b
logging.level.dev.langchain4j=DEBUG
quarkus.http.static-resources.enable=true
quarkus.http.static-resources.paths=/
# Controla abertura automática do navegador ao iniciar
# Pode ser desativado com: -Dtenebra.browser.auto-open=false
tenebra.browser.auto-open=true
# Quantidade máxima de mensagens mantidas no histórico de cada sessão
tenebra.history.max-size=30
tenebra.ai.structured=false
